# First, create a ConfigMap whose contents are used
# as the default.conf file in the web server. 
# This server uses /var/www/html as its
# root document directory. When the server gets a 
# request for *.php, it will forward that request
# to our PHP-FPM container.
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        
        # Set nginx to serve files from the shared volume!
        root   /var/www/html;
        server_name _;

        location / {
            try_files $uri $uri/ =404;
            index  index.php;
        }

        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-phpfpm-example-1
spec:
  ports:
  - nodePort: 32500
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-phpfpm-example-1
  type: NodePort
---
# Create a pod containing the PHP-FPM application (php-app)
# and nginx, each mounting the `shared-files` volume to their
# respective /var/www/html directories.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-phpfpm-example-1
spec:
  template:
    metadata:
      labels:
        app: nginx-phpfpm-example-1
    spec:
      containers:
      # Our PHP-FPM application
      - image: 127.0.0.1:31500/php-app:example-1
        imagePullPolicy: IfNotPresent
        name: app
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
        # Important! After this container has started, the PHP files
        # in our Docker image aren't in the shared volume. We need to 
        # get them into the shared volume. If we tried to write directly
        # to this volume from our Docker image the files wouldn't appear
        # in the nginx container.
        #
        # So, after the container has started, copy the PHP files from this
        # container's local filesystem (/app -- added via the Docker image) 
        # to the shared volume, which is mounted at /var/www/html.
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]
      
      # Our nginx container, which uses the configuration declared above,
      # along with the files shared with the PHP-FPM app.
      - image: nginx:1.7.9
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            mountPropagation: None
            subPath: default.conf
      
      # Our volumes
      volumes:
        # Create the shared files volume to be used in both pods
        - name: shared-files
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        
